[package]
name = "entity_benchmark"
version = "0.1.0"
authors = ["Tinco Andringa <mail@tinco.nl>"]

[dependencies]
entity_rust = { version =">= 0.0.8" }
lazy_static = "*"
shared-mutex = "*"
uuid = "*"
sdl2 = "0.19.0"
sdl2_ttf = "0.19.0"
ncollide = ">= 0.9.0"

